version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - internal_network

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=tms_db
      - POSTGRES_USER=tms_user
      - POSTGRES_PASSWORD=tms_pass
    volumes:
      - pgdata:/var/lib/postgresql/data  # ✅ fixed path
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "tms_user", "-d", "tms_db"]
      interval: 10s
      retries: 5

  app:
    build:
      context: ./frontend         
      dockerfile: Dockerfile      
    depends_on:
      - api
    ports:
      - 80:80
    networks:
      - internal_network

volumes:
  pgdata:

networks:
  internal_network:
    driver: bridge
